Add enums and bitfields to generate OD.h and fix #defines
oresat/oresat-configs pull request #40
Opened 2024-10-27 21:08 UTC by ryanpdx

Changes: 

- Add enums and bitfields to OD.h
- `#define OD_CNT_...` in OD.h are no longer hard-coded (this does break `oresat-firmware`, but I will have tiny fix PR for that as well)
- Fix a EMCY cob id bug when multiple cards exists (effects solar and rw)
- Remove some very old legacy code in CANopenNode file generator
- Remove whitespace in some yaml configs

2024-10-29 00:03 UTC, ThirteenFish requested changes
As far as I can tell this seems correct, a couple small things. Other ideas that are outside the scope of the PR:
- Set up `yamllint` (or similar, but this one is on pypi) in the CI to catch whitespace issues.
- Use the enums and bitfields in the generated OD definition (or generate a comment in the definition that points to the relevant type) so that there doesn't have to be a cast to use them. The difficulty is that for the bitfields, all the projects would have to be updated to access them using the new fields, and C enums are just super weird (although C23 looks like it improves them a bit?). The enums, while int by default, can be `__attribute__((packed))` to get down to the minimum size to hold the largest member, but the members themselves will still be ints, with a downcast on assignment.
- `static_assert()` as a double check that the bitfield union size is the right size (and also enum sizes if going with the packed enums, those are super easy to get wrong).

2024-10-31 01:09 UTC, ryanpdx commented on oresat_configs/_yaml_to_od.py
> +    return {key: bit_defs[key] for key in sorted_bit_defs_keys}
Moved the sorting logic to gen fw files script

2024-10-31 01:11 UTC, ryanpdx commented on oresat_configs/scripts/gen_fw_files.py
> -def format_name(string: str) -> str:
Yep, it is.

Those were leftovers from the eds to od script this script this file is derived from

2024-10-31 01:13 UTC, ryanpdx commented on oresat_configs/scripts/gen_fw_files.py
> +    lines.append(INDENT4 + "} fields;")
Interesting.

Personally, I am more use to non-anonymous style

2024-10-31 01:13 UTC, ryanpdx commented on oresat_configs/_yaml_to_od.py
> +    return {key: bit_defs[key] for key in sorted_bit_defs_keys}
and added the `static_assert()` checks

2024-10-31 01:36 UTC, ryanpdx commented on oresat_configs/_yaml_to_od.py
> +    return {key: bit_defs[key] for key in sorted_bit_defs_keys}
Oh, there may be a issue with using `static_assert()` with the zephyr arm compiler, still looking into it

2024-10-31 01:38 UTC, ThirteenFish commented on oresat_configs/_yaml_to_od.py
> +    return {key: bit_defs[key] for key in sorted_bit_defs_keys}
Need to add the `union` to the typename, they've not been `typedef`d away:
```python
        f"static_assert(sizeof(union {bitfield_name}) == sizeof({data_type}), "
```

2024-10-31 01:52 UTC, ThirteenFish approved these changes

2024-11-03 22:11 UTC, merged